version: '3'
services:
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: ${NEARBY_DB_USER}
      POSTGRES_PASSWORD:  ${NEARBY_DB_PASS}
      POSTGRES_DB: ${NEARBY_DB_NAME}
  nearby-component:
    env_file:
      - .env
    # image: kguinto/nearby-component
    build: .
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; npm start'
    volumes:
      - .:/nearby_service/
    ports:
      - "3003:3003"
    depends_on:
      - postgres
    environment:
      NEARBY_DB_NAME: "${NEARBY_DB_NAME}"
      NEARBY_DB_USER: "${NEARBY_DB_USER}"
      NEARBY_DB_PASS: "${NEARBY_DB_PASS}"
      NEARBY_DB_HOST: "postgres"
      NEARBY_GOOGLE_MAPS_API_KEY: "${NEARBY_GOOGLE_MAPS_API_KEY}"